import { StoredConfig } from './storedConfig'

export type BundledPreset = {
  pack: string
  sprite: string
  config: StoredConfig
}

export const presets: Record<string, BundledPreset> = {
  default: {'pack':'Essentials','sprite':'galaxySprite.png','config':{'user':{'speed':2,'rotationSpeed':2,'scaleFactor':1500,'cameraBound':100},'fractal':{'tour':50},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':true},'particle':{'particleSize':10,'particlesPerLayer':7500,'layers':4,'levels':3,'saturation':0.5,'sprites':['galaxySprite.png','galaxy2Sprite.png','galaxy3Sprite.png']},'orbit':{'a':5,'b':0.5,'c':5.5,'d':0.5,'e':0},'video':{'clips':['galaxy.mp4','earth.mp4'],'index':0}}},
  bassyndicate: {'pack':'Essentials','sprite':'bassyndicate.png','config':{'user':{'speed':0.5,'rotationSpeed':0.5,'scaleFactor':800,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':false,'switcheroo':false,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2,'b':0.69,'c':5.6,'d':1,'e':0.7},'particle':{'particleSize':200,'particlesPerLayer':20,'layers':10,'levels':4,'saturation':0.5,'sprites':['bassyndicate.png']}}},
  galaxySpace: {'pack':'Galaxy','sprite':'galaxySprite.png','config':{'user':{'speed':1,'rotationSpeed':3.25,'scaleFactor':2000,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':false,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':1.8,'b':0,'c':5.5,'d':0.5,'e':0.5},'particle':{'particleSize':50,'particlesPerLayer':166,'layers':4,'levels':3,'saturation':0.5,'sprites':['galaxySprite.png','galaxy2Sprite.png','galaxy3Sprite.png']}}},
  galaxySalad: {'pack':'Galaxy','sprite':'galaxySprite.png','config':{'user':{'speed':1,'rotationSpeed':-2.5,'scaleFactor':600,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':3,'b':0.69,'c':5.6,'d':1,'e':0.7},'particle':{'particleSize':200,'particlesPerLayer':12,'layers':10,'levels':2,'saturation':0,'sprites':['galaxySprite.png','galaxy2Sprite.png','galaxy3Sprite.png']}}},
  galaxyPortal: {'pack':'Galaxy','sprite':'galaxy3Sprite.png','config':{'user':{'speed':10,'rotationSpeed':4,'scaleFactor':900,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':false,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':3.2,'b':0.65,'c':5.5,'d':0.5,'e':0.5},'particle':{'particleSize':187,'particlesPerLayer':166,'layers':4,'levels':3,'saturation':0.5,'sprites':['galaxy3Sprite.png','galaxy2Sprite.png','galaxySprite.png']}}},
  galaxySpiral: {'pack':'Galaxy','sprite':'galaxy2Sprite.png','config':{'user':{'speed':4,'rotationSpeed':-2.5,'scaleFactor':300,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':3,'b':0.69,'c':5,'d':0.7,'e':1},'particle':{'particleSize':200,'particlesPerLayer':12,'layers':8,'levels':6,'saturation':0.3,'sprites':['galaxy2Sprite.png','galaxySprite.png','galaxy3Sprite.png']}}},
  sideSwirl: {'pack':'Essentials','sprite':'galaxy2Sprite.png','config':{'user':{'speed':6,'rotationSpeed':14.75,'scaleFactor':200,'cameraBound':500},'audio':{'soundThreshold':2,'ignoreTime':100},'effects':{'cyclone':false,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2.5,'b':0.69,'c':5.5,'d':0.5,'e':0.5},'particle':{'particleSize':15,'particlesPerLayer':2634,'layers':8,'levels':5,'saturation':0.5,'sprites':['galaxy2Sprite.png','galaxySprite.png','galaxy3Sprite.png']}}},
  eyeChase: {'pack':'Essentials','sprite':'fractaleye.png','config':{'user':{'speed':2.5,'rotationSpeed':4,'scaleFactor':800,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2,'b':0.69,'c':5.6,'d':0.6,'e':0.8},'particle':{'particleSize':175,'particlesPerLayer':20,'layers':10,'levels':2,'saturation':0.5,'sprites':['fractaleye.png']}}},
  crossheirSpin: {'pack':'Essentials','sprite':'crossheir.png','config':{'user':{'speed':1.5,'rotationSpeed':2,'scaleFactor':900,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':6.9,'b':0.02,'c':5.9,'d':1,'e':0.5},'particle':{'particleSize':7,'particlesPerLayer':9578,'layers':8,'levels':5,'saturation':0.5,'sprites':['crossheir.png']}}},
  pointerz: {'pack':'Sacred','sprite':'galaxySprite.png','config':{'user':{'speed':6,'rotationSpeed':2,'scaleFactor':1300,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':4.7,'b':0.27,'c':5.6,'d':1,'e':0.1},'particle':{'particleSize':7,'particlesPerLayer':9578,'layers':8,'levels':7,'saturation':0.5,'sprites':['galaxySprite.png','galaxy2Sprite.png','galaxy3Sprite.png']}}},
  dispersionTunnelSpin: {'pack':'Sacred','sprite':'galaxySprite.png','config':{'user':{'speed':0.5,'rotationSpeed':-2.5,'scaleFactor':1000,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':false,'wobWob':true,'switcheroo':false,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':5,'b':0.93,'c':5.8,'d':0.1,'e':0.2},'particle':{'particleSize':4,'particlesPerLayer':10139,'layers':12,'levels':4,'saturation':0.5,'sprites':['galaxySprite.png','galaxy2Sprite.png','galaxy3Sprite.png']}}},
  colorPortal: {'pack':'Sacred','sprite':'galaxySprite.png','config':{'user':{'speed':3,'rotationSpeed':12.5,'scaleFactor':600,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':true},'orbit':{'a':9,'b':0.35,'c':5.6,'d':1,'e':0.1},'particle':{'particleSize':7,'particlesPerLayer':5000,'layers':20,'levels':6,'saturation':0.5,'sprites':['galaxySprite.png','galaxy2Sprite.png','galaxy3Sprite.png']}}},
  edgeChaseSpin: {'pack':'Essentials','sprite':'galaxy3Sprite.png','config':{'user':{'speed':2,'rotationSpeed':5,'scaleFactor':1800,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':false,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':3.2,'b':0.08,'c':5.2,'d':0.7,'e':0.5},'particle':{'particleSize':35,'particlesPerLayer':2921,'layers':6,'levels':2,'saturation':0.5,'sprites':['galaxy3Sprite.png','galaxy2Sprite.png','galaxySprite.png']}}},
  ohSprite: {'pack':'Sprites','sprite':'ohSprite.png','config':{'user':{'speed':2,'rotationSpeed':4,'scaleFactor':800,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2,'b':0.69,'c':5.6,'d':0.1,'e':0.5},'particle':{'particleSize':185,'particlesPerLayer':10,'layers':10,'levels':4,'saturation':0.5,'sprites':['ohSprite.png']}}},
  circles: {'pack':'Essentials','sprite':'donut.png','config':{'user':{'speed':3.5,'rotationSpeed':2,'scaleFactor':1300,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':7.7,'b':0.2,'c':5.6,'d':1,'e':0.5},'particle':{'particleSize':7,'particlesPerLayer':9578,'layers':8,'levels':5,'saturation':0.5,'sprites':['donut.png']}}},
  squareMandala: {'pack':'Sacred','sprite':'galaxySprite.png','config':{'user':{'speed':5,'rotationSpeed':7.5,'scaleFactor':900,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':false,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2.5,'b':0.06,'c':5.9,'d':1,'e':0.5},'particle':{'particleSize':7,'particlesPerLayer':4832,'layers':20,'levels':5,'saturation':0.5,'sprites':['galaxySprite.png','galaxy2Sprite.png','galaxy3Sprite.png']}}},
  notes: {'pack':'Essentials','sprite':'musicNotes.png','config':{'user':{'speed':3,'rotationSpeed':3.25,'scaleFactor':600,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':false,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2.7,'b':0,'c':5.1,'d':0.6,'e':0.5},'particle':{'particleSize':149,'particlesPerLayer':35,'layers':10,'levels':4,'saturation':0,'sprites':['musicNotes.png','musicNotes2.png','musicNotes3.png']}}},
  noteExplosion: {'pack':'Essentials','sprite':'musicNoteExplosion.png','config':{'user':{'speed':2.5,'rotationSpeed':4,'scaleFactor':800,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2,'b':0.69,'c':5.6,'d':0.6,'e':0.8},'particle':{'particleSize':175,'particlesPerLayer':20,'layers':10,'levels':2,'saturation':0.7,'sprites':['musicNoteExplosion.png','musicNoteExplosion2.png','musicNoteExplosion.png']}}},
  fire: {'pack':'Elemental','sprite':'fire.png','config':{'user':{'speed':5,'rotationSpeed':-2.5,'scaleFactor':600,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':3,'b':0.69,'c':5.6,'d':1,'e':0.7},'particle':{'particleSize':200,'particlesPerLayer':12,'layers':10,'levels':2,'saturation':0,'sprites':['fire.png','fire2.png','fire3.png']}}},
  ice: {'pack':'Elemental','sprite':'ice.png','config':{'user':{'speed':5,'rotationSpeed':-2.5,'scaleFactor':600,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':3,'b':0.69,'c':5.6,'d':1,'e':0.7},'particle':{'particleSize':200,'particlesPerLayer':12,'layers':10,'levels':2,'saturation':0,'sprites':['ice.png']}}},
  shlump: {'pack':'Shlump','sprite':'shlump.png','config':{'user':{'speed':1,'rotationSpeed':0.5,'scaleFactor':800,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':false,'switcheroo':false,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2,'b':0.69,'c':5.6,'d':1,'e':0.7},'particle':{'particleSize':200,'particlesPerLayer':20,'layers':10,'levels':4,'saturation':0.5,'sprites':['shlump.png']}}},
  shlumpSkull: {'pack':'Shlump','sprite':'shlumpSkull.png','config':{'user':{'speed':7,'rotationSpeed':4,'scaleFactor':900,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':false,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2.6,'b':0.79,'c':5.8,'d':0,'e':0},'particle':{'particleSize':114,'particlesPerLayer':30,'layers':4,'levels':3,'saturation':0.9,'sprites':['shlumpSkull.png']}}},
  shlumpSalad: {'pack':'Shlump','sprite':'fractaleye.png','config':{'user':{'speed':1,'rotationSpeed':-2.5,'scaleFactor':600,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':3,'b':0.69,'c':5.6,'d':1,'e':0.9},'particle':{'particleSize':200,'particlesPerLayer':12,'layers':10,'levels':2,'saturation':0.2,'sprites':['fractaleye.png','shlumpSkull.png','shlump.png']}}},
  hyperShlump: {'pack':'Shlump','sprite':'shlump.png','config':{'user':{'speed':2.5,'rotationSpeed':3.75,'scaleFactor':200,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':5.4,'b':0.78,'c':5.5,'d':0.1,'e':0.5},'particle':{'particleSize':175,'particlesPerLayer':5,'layers':10,'levels':3,'saturation':0,'sprites':['shlump.png']}}},
  shlumpSpin: {'pack':'Shlump','sprite':'shlump.png','config':{'user':{'speed':2,'rotationSpeed':-5,'scaleFactor':1500,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2.8,'b':0.16,'c':5.8,'d':0.8,'e':0.1},'particle':{'particleSize':200,'particlesPerLayer':6,'layers':10,'levels':2,'saturation':0.5,'sprites':['shlump.png']}}},
  emorfikFire: {'pack':'Emorfik','sprite':'fire.png','config':{'user':{'speed':5,'rotationSpeed':-2.5,'scaleFactor':600,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':100,'b':0.69,'c':5.6,'d':1,'e':0.7},'particle':{'particleSize':200,'particlesPerLayer':12,'layers':10,'levels':2,'saturation':0,'sprites':['fire.png','fire2.png','fire3.png']},'video':{'clips':['EMORFIK14.mp4','EMORFIK13.mp4'],'index':0}}},
  weed: {'pack':'Essentials','sprite':'weed.png','config':{'user':{'speed':4.5,'rotationSpeed':4,'scaleFactor':800,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2.2,'b':0.69,'c':5.6,'d':0.6,'e':0.8},'particle':{'particleSize':175,'particlesPerLayer':20,'layers':10,'levels':2,'saturation':0.5,'sprites':['weed.png']}}},
  garbageMonsters: {'pack':'Sprites','sprite':'garbageMonster.png','config':{'user':{'speed':7,'rotationSpeed':6.5,'scaleFactor':800,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2,'b':0.24,'c':5.6,'d':0.6,'e':0.8},'particle':{'particleSize':165,'particlesPerLayer':20,'layers':4,'levels':2,'saturation':0,'sprites':['garbageMonster.png','garbageMonster2.png','garbageMonster.png']}}},
  garbageMan: {'pack':'Sprites','sprite':'garbageMan.png','config':{'user':{'speed':8,'rotationSpeed':11,'scaleFactor':600,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2.8,'b':0.81,'c':5.6,'d':0.6,'e':0.8},'particle':{'particleSize':200,'particlesPerLayer':20,'layers':4,'levels':2,'saturation':0,'sprites':['garbageMan.png']}}},
  choppingMen: {'pack':'Sprites','sprite':'choppingMan.png','config':{'user':{'speed':7,'rotationSpeed':6.5,'scaleFactor':800,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2,'b':0.24,'c':5.6,'d':0.6,'e':0.8},'particle':{'particleSize':165,'particlesPerLayer':20,'layers':4,'levels':2,'saturation':0,'sprites':['choppingMan.png','choppingMan2.png','choppingMan.png']}}},
  choppingHands: {'pack':'Sprites','sprite':'chopHand.png','config':{'user':{'speed':8,'rotationSpeed':11,'scaleFactor':600,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2.8,'b':0.81,'c':5.6,'d':0.6,'e':0.8},'particle':{'particleSize':200,'particlesPerLayer':20,'layers':4,'levels':2,'saturation':0,'sprites':['chopHand.png','chopHand2.png']}}},
  slimeHands: {'pack':'Sprites','sprite':'slimeHand3.png','config':{'user':{'speed':3.5,'rotationSpeed':6.5,'scaleFactor':800,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2.2,'b':0.24,'c':5.6,'d':0.6,'e':0.8},'particle':{'particleSize':175,'particlesPerLayer':20,'layers':4,'levels':2,'saturation':0.1,'sprites':['slimeHand3.png','slimeHand2.png','slimeHand.png']}}},
  honeycomb: {'pack':'Essentials','sprite':'honeycomb.png','config':{'user':{'speed':2,'rotationSpeed':-2.5,'scaleFactor':500,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':false,'shockwave':false},'orbit':{'a':2,'b':0.97,'c':5.6,'d':0.2,'e':0.7},'particle':{'particleSize':200,'particlesPerLayer':12,'layers':8,'levels':8,'saturation':0.3,'sprites':['honeycomb.png']}}},
  kaiber: {'pack':'Essentials','sprite':'kaiber.png','config':{'user':{'speed':0.5,'rotationSpeed':0.5,'scaleFactor':800,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':false,'switcheroo':false,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2,'b':0.69,'c':5.6,'d':1,'e':0.7},'particle':{'particleSize':200,'particlesPerLayer':20,'layers':10,'levels':4,'saturation':0.5,'sprites':['kaiber.png']}}},
  blackout: {'pack':'Essentials','sprite':'barbwire.png','config':{'user':{'speed':3.5,'rotationSpeed':-5,'scaleFactor':1000,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':10,'b':0,'c':5.5,'d':0.5,'e':0.5},'particle':{'particleSize':200,'particlesPerLayer':4,'layers':3,'levels':2,'saturation':0,'sprites':['barbwire.png']}}},
  emorfikIntroJumpy: {'pack':'Emorfik','sprite':'EmorfikChromeLogo.png','config':{'user':{'speed':3.5,'rotationSpeed':-5,'scaleFactor':1000,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':10,'b':0,'c':5.5,'d':0.5,'e':0.5},'particle':{'particleSize':200,'particlesPerLayer':4,'layers':3,'levels':2,'saturation':0,'sprites':['EmorfikChromeLogo.png']},'video':{'clips':['EmorfikIntro.mp4'],'index':0}}},
  emorfik: {'pack':'Emorfik','sprite':'emorfik.png','config':{'user':{'speed':1,'rotationSpeed':0.5,'scaleFactor':800,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':false,'switcheroo':false,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2,'b':0.69,'c':5.6,'d':1,'e':0.7},'particle':{'particleSize':200,'particlesPerLayer':20,'layers':10,'levels':4,'saturation':0.1,'sprites':['emorfik.png']}}},
  emorfikZombieWave: {'pack':'Emorfik','sprite':'EmorfikRed.png','config':{'user':{'speed':2,'rotationSpeed':2,'scaleFactor':1500,'cameraBound':100},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':true},'orbit':{'a':2.8,'b':0.16,'c':5.8,'d':0.8,'e':0.1},'particle':{'particleSize':200,'particlesPerLayer':6,'layers':10,'levels':2,'saturation':0,'sprites':['EmorfikRed.png']},'video':{'clips':['EMORFIK10.mp4','EMORFIK16.mp4'],'index':0}}},
  emorfikWireWhite: {'pack':'Emorfik','sprite':'barbwire.png','config':{'user':{'speed':7,'rotationSpeed':4,'scaleFactor':900,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':false,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2.6,'b':0.79,'c':5.8,'d':0,'e':0},'particle':{'particleSize':200,'particlesPerLayer':30,'layers':4,'levels':3,'saturation':0,'sprites':['barbwire.png']}}},
  emorfikWireLogo: {'pack':'Emorfik','sprite':'barbwire.png','config':{'user':{'speed':7,'rotationSpeed':4,'scaleFactor':900,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':false,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2.6,'b':0.79,'c':5.8,'d':0,'e':0},'particle':{'particleSize':130,'particlesPerLayer':30,'layers':4,'levels':3,'saturation':0.4,'sprites':['barbwire.png']},'video':{'clips':['EMORFIKLogoSpin.mp4'],'index':0}}},
  emorfikSkullVid: {'pack':'Emorfik','sprite':'skull.png','config':{'user':{'speed':7,'rotationSpeed':4,'scaleFactor':900,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':false,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2.6,'b':0.79,'c':5.8,'d':0,'e':0},'particle':{'particleSize':114,'particlesPerLayer':30,'layers':4,'levels':3,'saturation':0,'sprites':['skull.png']},'video':{'clips':['EMORFIKHead.mp4','EMORFIKHead2.mp4'],'index':0}}},
  emorfikSaladColor: {'pack':'Emorfik','sprite':'skull.png','config':{'user':{'speed':1,'rotationSpeed':-2.5,'scaleFactor':600,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':3,'b':0.69,'c':5.6,'d':1,'e':0.9},'particle':{'particleSize':200,'particlesPerLayer':12,'layers':10,'levels':2,'saturation':0,'sprites':['skull.png','barbwire.png','emorfik.png','emorfikRed.png']}}},
  emorfikSpin: {'pack':'Emorfik','sprite':'emorfik.png','config':{'user':{'speed':2,'rotationSpeed':-5,'scaleFactor':1500,'cameraBound':0},'audio':{'soundThreshold':2,'ignoreTime':250},'effects':{'cyclone':true,'wobWob':true,'switcheroo':true,'colorShift':true,'glow':true,'shockwave':false},'orbit':{'a':2.8,'b':0.16,'c':5.8,'d':0.8,'e':0.1},'particle':{'particleSize':200,'particlesPerLayer':6,'layers':10,'levels':2,'saturation':0,'sprites':['emorfik.png']}}},
}
